[package]
name = "quixotic-plecostomus-s2n"
version = "0.8.3"
license = "Apache-2.0"
edition = "2021"
repository = "https://github.com/praxis-proxy/pingora"
categories = ["asynchronous", "network-programming"]
keywords = ["async", "tls", "ssl", "pingora"]
description = """
S2N async APIs for Pingora.
"""

[lib]
name = "pingora_s2n"
path = "src/lib.rs"

[dependencies]
pingora-error = { version = "0.8.3", path = "../pingora-error", package = "quixotic-plecostomus-error" }
ring = "0.17.12"
s2n-tls = "0.3"
s2n-tls-tokio = "0.3"
