[package]
name = "quixotic-plecostomus-rustls"
version = "0.8.4"
license = "Apache-2.0"
edition = "2021"
repository = "https://github.com/praxis-proxy/pingora"
categories = ["asynchronous", "network-programming"]
keywords = ["async", "tls", "ssl", "pingora"]
description = """
RusTLS async APIs for Pingora.
"""

[lib]
name = "pingora_rustls"
path = "src/lib.rs"

[dependencies]
log = "0.4.34"
pingora-error = { version = "0.8.4", path = "../pingora-error", package = "quixotic-plecostomus-error" }
ring = "0.17.14"
rustls = { version = "0.23.43", features = ["ring"] }
rustls-native-certs = "0.7.3"
rustls-pemfile = "2.2.0"
rustls-pki-types = "1.15.1"
tokio-rustls = "0.26.4"
no_debug = "3.1.0"
